import { CourseTemplate } from "./CourseTypes";

export const courseTemplates: CourseTemplate[] = [
  {
    id: "blank",
    name: "Blank Course",
    description: "Start from scratch with a single empty module. Full control over every lesson and block.",
    category: "General",
    coverUrl: "",
    moduleCount: 1,
    lessonCount: 1,
    difficulty: "beginner" as const,
    modules: [
      { title: "Getting Started", lessons: [{ title: "Welcome", contentType: "text" }] },
    ],
  },
  {
    id: "mini",
    name: "Mini Course",
    description: "Short and focused — 3 modules with ~9 lessons. Perfect for lead magnets, quick wins, or single-topic deep dives.",
    category: "General",
    coverUrl: "",
    moduleCount: 3,
    lessonCount: 9,
    difficulty: "beginner" as const,
    modules: [
      { title: "Foundation", lessons: [
        { title: "Welcome & Overview", contentType: "video" },
        { title: "Core Concept Explained", contentType: "text" },
        { title: "Quick Start Exercise", contentType: "assignment" },
      ]},
      { title: "Core Content", lessons: [
        { title: "The Main Framework", contentType: "video" },
        { title: "Step-by-Step Walkthrough", contentType: "text" },
        { title: "Practice Session", contentType: "assignment" },
      ]},
      { title: "Wrap-Up", lessons: [
        { title: "Key Takeaways", contentType: "video" },
        { title: "Knowledge Check", contentType: "quiz" },
        { title: "Next Steps & Resources", contentType: "text" },
      ]},
    ],
  },
  {
    id: "masterclass",
    name: "Masterclass",
    description: "Comprehensive deep-dive with 8 modules and 30+ lessons. Full production course with assessments, assignments, and certification.",
    category: "Advanced",
    coverUrl: "",
    moduleCount: 8,
    lessonCount: 32,
    difficulty: "advanced" as const,
    modules: [
      { title: "Introduction & Foundations", lessons: [
        { title: "Welcome to the Masterclass", contentType: "video" },
        { title: "Prerequisites & Setup", contentType: "text" },
        { title: "The Big Picture", contentType: "video" },
        { title: "Core Terminology", contentType: "quiz" },
      ]},
      { title: "Core Principles", lessons: [
        { title: "Principle 1: Foundation", contentType: "video" },
        { title: "Principle 2: Strategy", contentType: "video" },
        { title: "Principle 3: Execution", contentType: "text" },
        { title: "Principles Deep Dive", contentType: "assignment" },
      ]},
      { title: "Advanced Techniques", lessons: [
        { title: "Advanced Method 1", contentType: "video" },
        { title: "Advanced Method 2", contentType: "video" },
        { title: "Expert Patterns", contentType: "text" },
        { title: "Technique Lab", contentType: "assignment" },
      ]},
      { title: "Real-World Applications", lessons: [
        { title: "Case Study 1", contentType: "video" },
        { title: "Case Study 2", contentType: "video" },
        { title: "Industry Analysis", contentType: "text" },
        { title: "Case Study Reflection", contentType: "assignment" },
      ]},
      { title: "Tools & Systems", lessons: [
        { title: "Tool Overview & Setup", contentType: "video" },
        { title: "System Architecture", contentType: "text" },
        { title: "Workflow Automation", contentType: "video" },
        { title: "Tool Mastery Exercise", contentType: "assignment" },
      ]},
      { title: "Optimization", lessons: [
        { title: "Measuring Success", contentType: "video" },
        { title: "Iteration Strategies", contentType: "text" },
        { title: "Common Pitfalls", contentType: "video" },
        { title: "Optimization Project", contentType: "assignment" },
      ]},
      { title: "Integration & Scale", lessons: [
        { title: "Scaling Your Approach", contentType: "video" },
        { title: "Team & Collaboration", contentType: "text" },
        { title: "Integration Patterns", contentType: "video" },
        { title: "Integration Challenge", contentType: "assignment" },
      ]},
      { title: "Final Project & Certification", lessons: [
        { title: "Final Project Brief", contentType: "video" },
        { title: "Project Work Session", contentType: "assignment" },
        { title: "Peer Review", contentType: "assignment" },
        { title: "Final Exam", contentType: "quiz" },
        { title: "Certificate & Graduation", contentType: "video" },
      ]},
    ],
  },
  {
    id: "workshop",
    name: "Workshop",
    description: "Hands-on workshop format with 4 modules. Live-friendly structure with exercises, demos, and a final project.",
    category: "Workshops",
    coverUrl: "",
    moduleCount: 4,
    lessonCount: 12,
    difficulty: "intermediate" as const,
    modules: [
      { title: "Workshop Prep", lessons: [
        { title: "Welcome & Materials", contentType: "video" },
        { title: "Setup Guide", contentType: "text" },
        { title: "Pre-Workshop Quiz", contentType: "quiz" },
      ]},
      { title: "Core Concepts & Demo", lessons: [
        { title: "Concept Overview", contentType: "video" },
        { title: "Live Demo Walkthrough", contentType: "video" },
        { title: "Hands-On Exercise", contentType: "assignment" },
      ]},
      { title: "Build Together", lessons: [
        { title: "Building Step 1", contentType: "video" },
        { title: "Building Step 2", contentType: "video" },
        { title: "Guided Practice", contentType: "assignment" },
      ]},
      { title: "Final Project", lessons: [
        { title: "Project Brief", contentType: "video" },
        { title: "Work Session", contentType: "assignment" },
        { title: "Showcase & Review", contentType: "assignment" },
      ]},
    ],
  },
  {
    id: "coaching",
    name: "Coaching Program",
    description: "5-module coaching framework with assessments, action plans, and accountability checkpoints. Ideal for coaches and mentors.",
    category: "Coaching",
    coverUrl: "",
    moduleCount: 5,
    lessonCount: 15,
    difficulty: "beginner" as const,
    modules: [
      { title: "Foundation & Goals", lessons: [
        { title: "Welcome & Course Overview", contentType: "video" },
        { title: "Defining Your Vision", contentType: "text" },
        { title: "Goal-Setting Framework", contentType: "assignment" },
      ]},
      { title: "Core Principles", lessons: [
        { title: "The Mindset Shift", contentType: "video" },
        { title: "Key Strategies", contentType: "text" },
        { title: "Self-Assessment Quiz", contentType: "quiz" },
      ]},
      { title: "Action Plan", lessons: [
        { title: "Building Your Roadmap", contentType: "video" },
        { title: "Weekly Action Steps", contentType: "text" },
        { title: "Accountability Check-In", contentType: "assignment" },
      ]},
      { title: "Overcoming Obstacles", lessons: [
        { title: "Common Pitfalls", contentType: "video" },
        { title: "Resilience Techniques", contentType: "text" },
        { title: "Case Study Analysis", contentType: "assignment" },
      ]},
      { title: "Growth & Next Steps", lessons: [
        { title: "Review & Reflection", contentType: "text" },
        { title: "Final Assessment", contentType: "quiz" },
        { title: "Your Ongoing Journey", contentType: "video" },
      ]},
    ],
  },
  {
    id: "membership",
    name: "Membership Course",
    description: "Evergreen content structure with 6 modules. Designed for membership sites with drip content, community discussions, and ongoing updates.",
    category: "Membership",
    coverUrl: "",
    moduleCount: 6,
    lessonCount: 18,
    difficulty: "intermediate" as const,
    modules: [
      { title: "Welcome & Onboarding", lessons: [
        { title: "Welcome to the Membership", contentType: "video" },
        { title: "How This Works", contentType: "text" },
        { title: "Community Guidelines", contentType: "text" },
      ]},
      { title: "Month 1: Foundation", lessons: [
        { title: "Getting Started", contentType: "video" },
        { title: "Core Concepts", contentType: "text" },
        { title: "First Assignment", contentType: "assignment" },
      ]},
      { title: "Month 2: Building", lessons: [
        { title: "Building Your Base", contentType: "video" },
        { title: "Advanced Strategies", contentType: "video" },
        { title: "Monthly Check-In", contentType: "assignment" },
      ]},
      { title: "Month 3: Growth", lessons: [
        { title: "Growth Tactics", contentType: "video" },
        { title: "Community Spotlight", contentType: "text" },
        { title: "Growth Challenge", contentType: "assignment" },
      ]},
      { title: "Month 4: Mastery", lessons: [
        { title: "Mastery Techniques", contentType: "video" },
        { title: "Expert Interviews", contentType: "video" },
        { title: "Final Project", contentType: "assignment" },
      ]},
      { title: "Ongoing Resources", lessons: [
        { title: "Library of Resources", contentType: "text" },
        { title: "Monthly Q&A Archive", contentType: "video" },
        { title: "What's Next", contentType: "text" },
      ]},
    ],
  },
  {
    id: "challenge",
    name: "Challenge Course",
    description: "Fast-paced daily challenge with 2 weekly modules. High engagement format with daily tasks, community check-ins, and a final celebration.",
    category: "Challenges",
    coverUrl: "",
    moduleCount: 2,
    lessonCount: 14,
    difficulty: "beginner" as const,
    modules: [
      { title: "Week 1: Foundation", lessons: [
        { title: "Day 1: Welcome & Why", contentType: "video" },
        { title: "Day 2: The First Step", contentType: "text" },
        { title: "Day 3: Building Momentum", contentType: "video" },
        { title: "Day 4: Reflection & Adjust", contentType: "assignment" },
        { title: "Day 5: Deep Work", contentType: "text" },
        { title: "Day 6: Community Check-In", contentType: "assignment" },
        { title: "Day 7: Week 1 Review", contentType: "quiz" },
      ]},
      { title: "Week 2: Acceleration", lessons: [
        { title: "Day 8: Leveling Up", contentType: "video" },
        { title: "Day 9: Advanced Strategy", contentType: "text" },
        { title: "Day 10: Push Through", contentType: "video" },
        { title: "Day 11: Peer Review", contentType: "assignment" },
        { title: "Day 12: Mastery Session", contentType: "text" },
        { title: "Day 13: Final Prep", contentType: "video" },
        { title: "Day 14: Completion & Certificate", contentType: "quiz" },
      ]},
    ],
  },
];
