import { CourseTemplate } from "./CourseTypes";

export const courseTemplates: CourseTemplate[] = [
  {
    id: "tmpl-coaching",
    name: "Coaching Program",
    description: "5-module coaching framework with assessments and action plans. Perfect for life coaches, business coaches, and mentors.",
    category: "Business",
    coverUrl: "",
    moduleCount: 5,
    lessonCount: 15,
    difficulty: "beginner",
    modules: [
      { title: "Foundation & Goals", lessons: [{ title: "Welcome & Course Overview", contentType: "video" }, { title: "Defining Your Vision", contentType: "text" }, { title: "Goal-Setting Framework", contentType: "assignment" }] },
      { title: "Core Principles", lessons: [{ title: "The Mindset Shift", contentType: "video" }, { title: "Key Strategies", contentType: "text" }, { title: "Self-Assessment Quiz", contentType: "quiz" }] },
      { title: "Action Plan", lessons: [{ title: "Building Your Roadmap", contentType: "video" }, { title: "Weekly Action Steps", contentType: "text" }, { title: "Accountability Check-In", contentType: "assignment" }] },
      { title: "Overcoming Obstacles", lessons: [{ title: "Common Pitfalls", contentType: "video" }, { title: "Resilience Techniques", contentType: "text" }, { title: "Case Study Analysis", contentType: "assignment" }] },
      { title: "Growth & Next Steps", lessons: [{ title: "Review & Reflection", contentType: "text" }, { title: "Final Assessment", contentType: "quiz" }, { title: "Your Ongoing Journey", contentType: "video" }] },
    ],
  },
  {
    id: "tmpl-seo",
    name: "SEO Course",
    description: "7-module SEO curriculum from keyword research to technical SEO. Includes site audits and ranking strategies.",
    category: "Marketing",
    coverUrl: "",
    moduleCount: 7,
    lessonCount: 21,
    difficulty: "intermediate",
    modules: [
      { title: "SEO Fundamentals", lessons: [{ title: "What is SEO?", contentType: "video" }, { title: "How Search Engines Work", contentType: "text" }, { title: "SEO Terminology", contentType: "quiz" }] },
      { title: "Keyword Research", lessons: [{ title: "Finding Your Keywords", contentType: "video" }, { title: "Keyword Tools & Analysis", contentType: "text" }, { title: "Keyword Mapping Exercise", contentType: "assignment" }] },
      { title: "On-Page SEO", lessons: [{ title: "Title Tags & Meta Descriptions", contentType: "video" }, { title: "Content Optimization", contentType: "text" }, { title: "Internal Linking", contentType: "video" }] },
      { title: "Technical SEO", lessons: [{ title: "Site Structure & Crawlability", contentType: "video" }, { title: "Schema Markup", contentType: "text" }, { title: "Core Web Vitals", contentType: "text" }] },
      { title: "Content Strategy", lessons: [{ title: "Content That Ranks", contentType: "video" }, { title: "Topic Clusters", contentType: "text" }, { title: "Content Calendar", contentType: "assignment" }] },
      { title: "Link Building", lessons: [{ title: "White Hat Link Building", contentType: "video" }, { title: "Outreach Strategies", contentType: "text" }, { title: "Link Audit", contentType: "assignment" }] },
      { title: "Measurement & SEO", lessons: [{ title: "Google Analytics & Search Console", contentType: "video" }, { title: "SEO Reporting", contentType: "text" }, { title: "Final Project: Site Audit", contentType: "assignment" }] },
    ],
  },
  {
    id: "tmpl-14day",
    name: "14-Day Challenge",
    description: "Fast-paced daily challenge with email-style lesson drip. High engagement, low drop-off.",
    category: "Personal Development",
    coverUrl: "",
    moduleCount: 2,
    lessonCount: 14,
    difficulty: "beginner",
    modules: [
      { title: "Week 1: Foundation", lessons: [
        { title: "Day 1: Welcome & Why", contentType: "video" },
        { title: "Day 2: The First Step", contentType: "text" },
        { title: "Day 3: Building Momentum", contentType: "video" },
        { title: "Day 4: Reflection & Adjust", contentType: "assignment" },
        { title: "Day 5: Deep Work", contentType: "text" },
        { title: "Day 6: Community Check-In", contentType: "assignment" },
        { title: "Day 7: Week 1 Review", contentType: "quiz" },
      ]},
      { title: "Week 2: Acceleration", lessons: [
        { title: "Day 8: Leveling Up", contentType: "video" },
        { title: "Day 9: Advanced Strategy", contentType: "text" },
        { title: "Day 10: Push Through", contentType: "video" },
        { title: "Day 11: Peer Review", contentType: "assignment" },
        { title: "Day 12: Mastery Session", contentType: "text" },
        { title: "Day 13: Final Prep", contentType: "video" },
        { title: "Day 14: Completion & Certificate", contentType: "quiz" },
      ]},
    ],
  },
  {
    id: "tmpl-academy",
    name: "Video Academy",
    description: "Video-first course with downloadable resources. Best for tutorials, software demos, and creative skills.",
    category: "Web Development",
    coverUrl: "",
    moduleCount: 4,
    lessonCount: 16,
    difficulty: "beginner",
    modules: [
      { title: "Getting Started", lessons: [{ title: "Intro & Setup", contentType: "video" }, { title: "Tools You Need", contentType: "video" }, { title: "Quick Start Guide", contentType: "text" }, { title: "Download Resources", contentType: "download" }] },
      { title: "Core Skills", lessons: [{ title: "Fundamental Concepts", contentType: "video" }, { title: "Hands-On Practice", contentType: "video" }, { title: "Common Patterns", contentType: "text" }, { title: "Practice Exercise", contentType: "assignment" }] },
      { title: "Advanced Topics", lessons: [{ title: "Going Deeper", contentType: "video" }, { title: "Real-World Examples", contentType: "video" }, { title: "Best Practices", contentType: "text" }, { title: "Knowledge Check", contentType: "quiz" }] },
      { title: "Final Project", lessons: [{ title: "Project Overview", contentType: "video" }, { title: "Build Along", contentType: "video" }, { title: "Submit Your Work", contentType: "assignment" }, { title: "Course Wrap-Up", contentType: "video" }] },
    ],
  },
  {
    id: "tmpl-certification",
    name: "Certification Track",
    description: "Rigorous program with exams, practical assessments, and a final certification project.",
    category: "Business",
    coverUrl: "",
    moduleCount: 6,
    lessonCount: 18,
    difficulty: "advanced",
    modules: [
      { title: "Prerequisites & Intro", lessons: [{ title: "Certification Overview", contentType: "video" }, { title: "Prerequisite Knowledge", contentType: "text" }, { title: "Entry Assessment", contentType: "quiz" }] },
      { title: "Core Module 1", lessons: [{ title: "Theory & Concepts", contentType: "video" }, { title: "Practical Application", contentType: "text" }, { title: "Module Exam 1", contentType: "quiz" }] },
      { title: "Core Module 2", lessons: [{ title: "Advanced Theory", contentType: "video" }, { title: "Case Studies", contentType: "text" }, { title: "Module Exam 2", contentType: "quiz" }] },
      { title: "Core Module 3", lessons: [{ title: "Expert Techniques", contentType: "video" }, { title: "Real Project Simulation", contentType: "assignment" }, { title: "Module Exam 3", contentType: "quiz" }] },
      { title: "Practical Assessment", lessons: [{ title: "Project Brief", contentType: "video" }, { title: "Work Session", contentType: "assignment" }, { title: "Peer Review", contentType: "assignment" }] },
      { title: "Final Certification", lessons: [{ title: "Final Exam Prep", contentType: "text" }, { title: "Final Exam", contentType: "quiz" }, { title: "Certificate Issuance", contentType: "video" }] },
    ],
  },
  {
    id: "tmpl-ai-bootcamp",
    name: "AI Bootcamp",
    description: "Cutting-edge AI curriculum. Covers prompt engineering, AI tools, and integrating AI into workflows.",
    category: "Data Science",
    coverUrl: "",
    moduleCount: 5,
    lessonCount: 20,
    difficulty: "intermediate",
    modules: [
      { title: "AI Foundations", lessons: [{ title: "What is AI?", contentType: "video" }, { title: "LLMs Explained", contentType: "text" }, { title: "AI Ethics & Safety", contentType: "video" }, { title: "Knowledge Check", contentType: "quiz" }] },
      { title: "Prompt Engineering", lessons: [{ title: "Anatomy of a Prompt", contentType: "video" }, { title: "Advanced Prompt Techniques", contentType: "text" }, { title: "Prompt Patterns", contentType: "assignment" }, { title: "Prompt Challenge", contentType: "quiz" }] },
      { title: "AI Tools & Workflows", lessons: [{ title: "Tool Overview", contentType: "video" }, { title: "Automation Workflows", contentType: "text" }, { title: "Building with AI APIs", contentType: "video" }, { title: "Tool Integration Lab", contentType: "assignment" }] },
      { title: "Content Generation", lessons: [{ title: "Writing with AI", contentType: "video" }, { title: "Image & Media Generation", contentType: "text" }, { title: "Code Generation", contentType: "video" }, { title: "Content Creation Project", contentType: "assignment" }] },
      { title: "AI Strategy", lessons: [{ title: "Building AI Products", contentType: "video" }, { title: "AI Roadmap", contentType: "text" }, { title: "Final Project", contentType: "assignment" }, { title: "Course Wrap-Up", contentType: "quiz" }] },
    ],
  },
];
